### ISSUE TITLE
Proper Sledgehammer interface

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#10]
> https://bitbucket.org/zmaths/isabelle2019-vsce/issues/11/proper-sledgehammer-interface
> @m-fleury 
> Use something like transient to provide insert sledgehammer proof, aka make lsp-isar-insert-sledgehammer usable directly.

**Comment by m-fleury** [comment]
> @m-fleury 
> This is now done in 6fbcb3c (it also has a keybinding), but I have not really used and tested it yet.

**Comment by m-fleury** [comment]
It might be interesting to try it something along the line of

```
(define-key isar-mode-map (kbd "C-c s")
  (lambda ()
    (progn
      (insert "sledgehammer")
      (lsp-isar-sledgehammer))))
```
(untested, but this is along @gh-salt's idea this week)

**Comment by gh-salt** [comment]
vampire is missing to the list of solvers

**Comment by m-fleury** [comment]
done in  4e319b8.

**Comment by m-fleury** [comment]
> It might be interesting to try it something along the line of
> 
> ```
> (define-key isar-mode-map (kbd "C-c s")
>   (lambda ()
>     (progn
>       (insert "sledgehammer")
>       (lsp-isar-sledgehammer))))
> ```
> 
> (untested, but this is along @gh-salt's idea this week)

@gh-salt
In 1b9cb8f, I have added the function doing exactly that. It is named `lsp-isar-insert-sledgehammer-and-call` and it is bound on `C-c C-s`.

**Comment by m-fleury** [comment]
According to https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html:
> Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them. 

So C-c s is a actually bad keybinding (I am opened to ideas for a better one).

**Comment by gh-salt** [comment]
for spacemacs, the obvious keybinding would be SPC-m s. Is there an equivalent to SPC-m in emacs?

**Comment by gh-salt** [comment]
Another feature that would be nice to have is that the only offered options are the ones where a proof has been found (because the current behaviour of erasing sledgehammer when asking for say, the cvc4 proof when cvc4 found no proof is annoying if it happens by mistake)

**Comment by m-fleury** [comment]
There are two parts here.

1. What to do if there is no proof.
1. Dynamic stuff

For part 2, that means updating the view while viewing the menu (you view the results while sledgehammer results are coming). I am not sure about that.

For part 1, I am tempted to add an explicit 'd' to delete the sledgehammer call and otherwise only delete if something is inserted.

**Comment by gh-salt** [comment]
I am happy with your proposal for 1 and I don't mind ignoring 2.

**Comment by m-fleury** [comment]
The current behaviour is not optimal, because you exit transient mode and have to reopen it. I have to look at the transient doc.

**Comment by m-fleury** [comment]
Another improvement would be that [C-c C-m] does not insert a sledgehammer call if there is already one at the current position and simply opens the transient interface. That way there is no need anymore for [C-c m] and we avoid using both keybindings that are way to close to be safely used.

Opinions?

**Comment by m-fleury** [comment]
@gh-salt I had a look at [Spacemacs keybindings](https://develop.spacemacs.org/doc/DOCUMENTATION.html#binding-keys), but I don't get it (`(spacemacs/set-leader-keys-for-major-mode 'isar-mode "s" 'lsp-isar-insert-sledgehammer-and-call)` does not work).

**Comment by gh-salt** [comment]
I'll look into it as soon as I find the time.

**Comment by m-fleury** [comment]
I found it. I have now bound the command to «,ii», but I don't really have an opinion on that. The first "i" stands for isar and the second for "insert-sledgehammer". If we ever add another command, it would be ",i." where "." is another letter or command.


The problem was that isar-mode was not a real mode. Hence 'isar-mode did not work as expected. (I guess this proves once more that I am too stupid for emacs lisp...)

**Comment by m-fleury** [comment]
«,is» opens the transient interface for sledgehammer without inserting the call.

**Comment by gh-salt** [comment]
the `,ii` command prints sledgehammer exactly where the cursor is, so if I have a line 
```
  using mylemma_
```
where the `_` is the position of the cursor, then `,ii` results in 
```
  using mylemmasledgehammer
```
An improved behaviour would be to insert a space before sledgehammer if there is none, to obtain
```
  using mylemma sledgehammer
```

**Comment by m-fleury** [comment]
it should now do that (even if the cursor is at "using m_ylemmas").

However, I probably got some cases wrong in my patch.

**Comment by gh-salt** [comment]
There is a weird behaviour when inserting sledgehammer or try0 at the end of some lines, esp. ending with ')' but also after a cartouche or some letters (e.g. 'P' for some reason)
