### ISSUE TITLE
check and update readme (in spacemacs-isabelle)

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#12]
> @gh-salt
> isabelle2018 → isabelle2019 + check the rest

**Comment by m-fleury** [comment]
It might be interesting to #11 to simplify installation

**Comment by m-fleury** [comment]
I have added stuff in the [README.org](https://github.com/m-fleury/isabelle-release/blob/isabelle2019-more-vscode/src/Tools/emacs-lsp/spacemacs_layers/isabelle/README.org), including pictures.

I have also linked this readme from the overall readme.

**Comment by m-fleury** [comment]
Use straight directly from #11 and force developers on spacemacs to use [this method to use the local version](https://emacs.stackexchange.com/questions/20453/how-to-use-a-local-version-of-a-package-in-spacemacs)?

**Comment by gh-salt** [comment]
The git clone URL in the readme is only usable by project members. Is this intentional? (Using the http one would make more sense I believe)
