### ISSUE TITLE
try0 doesn't print proof in lsp-isar-output

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#14]
When try0 finds a proof, *sometimes* it prints the result only at the bottom of the main emacs window (where the messages usually appear). It could be linked to this error message:
`Error running timer: (void-variable lsp-isar-output-last-seen-prover)`

**Comment by m-fleury** [comment]
I am not sure the commit fixes it. It makes sure the variable is declared. However, I suspect that the non-printing comes from somewhere else (usually moving the cursor to the previous line and back works).
