### ISSUE TITLE
Try0 result

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#18]
The result of try0 can be extracted by
    (lsp-isar-insert-sledgehammer "Try this" nil nil)

The code of `lsp-isar-insert-sledgehammer` needs to be generalised a bit, i.e., parametrised by the command (either "sledgehammer" or "try0") and renamed to `lsp-isar-insert-sendback`. Then binding it to a keybinding will be trivial.

I don't believe an interface like transient is required, since there is a single outcome.

@gh-salt You seem to insert way more try0 than I do, so this has a higher priority for you than for me

**Comment by gh-salt** [comment]
yes definitely! I'll look into it as soon as I find the time.

**Comment by m-fleury** [comment]
The commits are in the RC2 branch, not the main branch. I have no clue about the keybinding. You should probably decide for a system what is first level and what is second level.

**Comment by m-fleury** [comment]
It is now part of the 2020 branch
