### ISSUE TITLE
delete-trailing-whitespace also deletes some end double-quotes

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#20]
When launching the emacs function delete-trailing-whitespace (in spacemacs SPC x d w) sometimes double-quotes (") appearing at the end of a line get deleted.

I think this also happens from time to time when introducing a carriage return in the middle of a line ending with double quotes but I never managed to isolate the phenomenon in that particular use-case, while it *seems* stable with delete-trailing-whitespace.

**Comment by m-fleury** [comment]
I always assumed that this is an emacs bug… I will look into it.

**Comment by m-fleury** [comment]
I got the syntax table wrong: quotes were accidentally marked as whitespace characters. Fixed by https://github.com/m-fleury/isar-mode/commit/ba869611e7cab5bcde5bb6dbb72124be09d09d4d. You just need to pull isar-mode.

**Comment by gh-salt** [comment]
Thanks!
