### ISSUE TITLE
inconsistent information in *lsp-isar-progress*

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#22]
In *lsp-isar-progress*, I have 
```
<Thy_Name> 1001 / 2001, ✖: 0, ⌛:0
```
although I am at the end of the `Thy_Name.thy` file.

**Comment by m-fleury** [comment]
I cannot reproduce it.

**Comment by m-fleury** [comment]
Duplicate of #28 with less information.
