### ISSUE TITLE
deactivate lsp (light start up mode)

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#23]
In some particular circumstance, it could be useful to start emacs-isabelle without the lsp back-end (e.g., to have a quick look at someone's files)

**Comment by m-fleury** [comment]
Use `(setq lsp-isar-use-lsp nil)` to start without lsp.

**Comment by m-fleury** [comment]
@gh-salt Does
```
spacemacs --eval "(setq lsp-isar-use-lsp nil)" ~/test/Scratch2.thy
```
works for what you had in mind?

**Comment by gh-salt** [comment]
Yes it does. Thanks!
