### ISSUE TITLE
no indentation when inserting new line with vim bindings "o" and "O"

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#24]
The line where the curso originally was is not indented in this case.

**Comment by m-fleury** [comment]
If I understand the code correctly, there does not seem to be a simple solution for that. Basically the only solution is to make sure that the line is already indented when pressing 'o'.

**Comment by m-fleury** [comment]
Unless there is a way hook into evil-insert-line-above and call the indentation function, I do not see a good solution. If you really want it, you can advise the function, but this is out of the scope of this project.

**Comment by m-fleury** [comment]
@gh-salt This is the way to go.

```
    (defun evil-insert-line-below-and-indent ()
      (interactive)
      (funcall indent-line-function)
      (evil-open-below 1))
    (defun evil-insert-line-above-and-indent ()
      (interactive)
      (funcall indent-line-function)
      (evil-open-above 1))
    (define-key evil-normal-state-map (kbd "o") 'evil-insert-line-below-and-indent)
    (define-key evil-normal-state-map (kbd "O") 'evil-insert-line-above-and-indent)
```

This probably works in all modes.
