### ISSUE TITLE
Align everything in progress buffer

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#27]
```
Scratch                                                              215 / 226, ✖: 1, ⌛:0
Scrath_With_A_Very_Very_Very_Long_Name     3 / 3,     ✖: 0, ⌛:0
```

The proper solution is to remember the position of the symbols in the line across invocations.
```
Scrath_With_A_Very_Very_Very_Long_Name    |3 / |3, |✖: |0, |⌛: |0
```

**Comment by m-fleury** [comment]
@gh-salt is that what you imagined?
![image](https://user-images.githubusercontent.com/41836833/82694552-ba543e80-9c63-11ea-90df-bb5025867d3c.png)

**Comment by m-fleury** [comment]
I added a feature on top of that. The function `lsp-isar-progress-theory-name-map` can be overwritten to do any transformation on the theory name. For example: 
```
        [WB]_Transition_System 10459 / 10459, ✖:  0, ⌛:  0
[WB]_Transition_System_Restart  1000 /  1000, ✖:  0, ⌛:  0
                  [WB]_Clauses   344 /   344, ✖:  0, ⌛:  0
             [WB]_All_Literals   377 /   377, ✖:  0, ⌛:  0
                [WB]_Algorithm  3170 /  3170, ✖:  0, ⌛:  0
        [WB]_Algorithm_Restart    59 /  1134, ✖:  0, ⌛:  0
```
I replaced the prefix "Watched_Literals" by "[WB]" because it is much shorter. This is probably not useful for you (unless you want to shorten "Non_Ground").

**Comment by gh-salt** [comment]
> @gh-salt is that what you imagined?
> ![image](https://user-images.githubusercontent.com/41836833/82694552-ba543e80-9c63-11ea-90df-bb5025867d3c.png)

Something like this, yes. It looks much better than initially! Thanks!

**Comment by gh-salt** [comment]
The latest feature you added is also a nice idea, although my names are too different to benefit from it.

By the way, as far as I am concerned, this issue could be closed.
