### ISSUE TITLE
Line length of output/state buffer

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#34]
@gh-salt 

In another branch(`Isabelle2020-more-vscode_lsp-protcol`), I have added the possibility to increase the length of line in the output/state buffer. Basically, we notify the Isabelle LSP server that from now on, we want longer lines. It does not update the current goal.

Questions:
  1. Do we want that feature? And does it make sense to have that?
  2. Should that automatically follow buffer resizing?

I am not certain that this is the best possible example, but here is one (it is the output produced by a `done` of a lemma):

Example with length 80:
![output_buffer_80](https://user-images.githubusercontent.com/41836833/86323632-7cbcdb00-bc3d-11ea-98cc-9165644091c6.png)

Example with length 120 (after calling `(lsp-isar-output-set-size 120)`), more of the buffer is used:
![output_buffer_120](https://user-images.githubusercontent.com/41836833/86323633-7d557180-bc3d-11ea-9943-11b06cec319e.png)

(NB: Isabelle is still in charge of optimal linebreak, we are just allowing it to put more text per line…)

**Comment by gh-salt** [comment]
I think it would be a great feature, especially if it follows by default the window resizing.

**Comment by m-fleury** [comment]
Now included in the default branch.
