### ISSUE TITLE
Same question asked twice when opening thy file

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#35]
When I open a thy file that is not part of a know project, lsp asks me what to do with it twice.
I am referring to the following:
```
<file>.thy is not part of any project. Select action:

i==>Import project root <path>.
I==>Import project by selecting root directory interactively.
d==>Do not ask again ...
D==> Do not ask again ...
n==>Do nothing...
```

**Comment by m-fleury** [comment]
Should be fixed now (it was in my code: I was running the `(lsp) function twice, hence the question was shown twice)
