### ISSUE TITLE
package cl deprecated 

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#40]
It would be cool to find which package has not yet dealt with this package, that makes a warning "cl package deprecated" appear at each start.

It doesn't seem to be dash.el

**Comment by m-fleury** [comment]
Following https://emacs.stackexchange.com/questions/58489/how-do-i-debug-package-cl-is-deprecated, the culprit seems to be: https://github.com/rolandwalker/list-utils (I don't want to link it, but it is issue 6). Apparently updated is breaking tests, so you will have to live with it...

**Comment by m-fleury** [comment]
But test the same on your spacemacs -- there might more than one package importing it.

**Comment by m-fleury** [comment]
Other source of problems: origami. This has already been reported there too.
