### ISSUE TITLE
Update README.org

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#43]
In the install instructions, Isabelle2019 is used...

**Comment by tani** [comment]
You can use Isabelle2020 and 2021. In the fact, I am using them.

**Comment by gh-salt** [comment]
The text in "Install (as a developer) > spacemacs > Create the private layer lisp-mode" (that should be lsp-mode) also needs some work since it seems the lsp-mode layer has disappeared from the repo. @m-fleury are you using the official spacemacs lsp layer instead now?

PS: Hello @tani , thanks for your answer. :)  In fact I am switching to Isabelle2021 (from 2020) and checking what needs to be improved in the Readme along the way. I opened this issue as a kind of todo list. Don't hesitate to report here if you stumble upon anything that needs to be updated in the readme.

**Comment by m-fleury** [comment]
Are you using master instead of develop for spacemacs?

**Comment by tani** [comment]
@gh-salt  Ah, thank you for the explanation. I'll write it if I found some update.

I am doom-emacs user. I'd like to contribute my configuration to this readme.
However, I feel better contributing my update to the official doom repository.
Which do you prefer?

**Comment by tani** [comment]
If @m-fleury doesn't mind it, I suggest changing the repository name. `isabelle-release` looks like the just mirror of the official repository. I missed this repository when I searched such projects by Google.

**Comment by m-fleury** [comment]
I also have a doom config for Isabelle actually (but I stopped using it).


As far as I know, there are 3 people using Isabelle/emacs*, so I am not certain that contributing your configuration to the official doom makes much sense. But I don't have an opinion on that.

* well until your message I thought that number was 2 so my numbers might be wildly off.

**Comment by gh-salt** [comment]
I am using develop for spacemacs.

For lsp, all that there is to do is to add lsp in the list of layers along with isabelle, correct?

**Comment by m-fleury** [comment]
Ah, my c-c++ config is probably already importing lsp transitively. Yes, adding lsp should be sufficient.

**Comment by gh-salt** [comment]
> If @m-fleury doesn't mind it, I suggest changing the repository name. `isabelle-release` looks like the just mirror of the official repository. I missed this repository when I searched such projects by Google.

This topic should be moved to another issue.

**Comment by gh-salt** [comment]
> Ah, my c-c++ config is probably already importing lsp transitively. Yes, adding lsp should be sufficient.

I'll updatet the readme then.

**Comment by gh-salt** [comment]
In "Post-Installation > Adding the AFP" the path contains "Isabelle2021". Shouldn't it be "Isabelle2021-vsce"?

**Comment by m-fleury** [comment]
Yes. 

At some point, I could also change Isabelle such that it "Isabelle2021" instead of "Isabelle2021-vsce" (aka uses the same configuration files as the release).

**Comment by gh-salt** [comment]
I would prefer that these stay separated, but we can discuss about it at our next meeting.
