### ISSUE TITLE
automatic indentation

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#7]
> @gh-salt
> automatic indentation when using tab on selected text would be a cool feature (but it is far from critical)

**Comment by m-fleury** [comment]
> @m-fleury 
>  Let me document where to find inspiration. Just in case that motivates you to write the code 😉
>
> The relevant Scala code is in file src/Tools/jEdit/src/text_structure.scala, in object:
> 
> `object Indent_Rule extends IndentRule`
>
> The abstract idea is to find the last line that starts with a keyword (or the last two line). Then depending on the the statuses of the keywords (quasi-command, command, …), we know what is the indentation.
>
‌> It might be better to ignore entirely the code I have written (it loops in some cases).

**Comment by m-fleury** [comment]
> @m-fleury 
> The looping is now fixed, but indentation is still buggy.

**Comment by gh-salt** [comment]
I assume issue #15 is related to this.

**Comment by m-fleury** [comment]
I finally rewrote the indentation from scratch. It is probably as buggy as before, but now I am able to fix bugs...

One slightly confusing thing: indentation when you press enter. Therefore, it seems wrong for a long time:

    text "Here is the line"
      lemma "This line seems wrong as the cursor is at "|

becomes after pressing enter:

    text "Here is the line"
    lemma "This line seems wrong as the cursor is at "
      |

(I don't know if electric-indent-mode is activated by default in spacemacs. If not, indentation will not happen when pressing enter).

To try it out:
`(setq lsp-isar-experimental t lsp-isar-indent-trace-indent nil)`

C-j forces line break without indentation of the current line.

**Comment by gh-salt** [comment]
Cool! I'll try it next week and let you know.

**Comment by m-fleury** [comment]
The `done` is wrong in:

```
   have P if "P ==> P" for P
     apply (rule that)
     subgoal sorry
       done
```
